stages:
  - image

.debos:
  stage: image
  image:
    name: ghcr.io/go-debos/debos:main
    entrypoint: [ "" ]
  tags:
    - kvm
  before_script:
    - mkdir -p out
  artifacts:
    expire_in: 1 week
    paths:
      - out

ci images:
  extends: .debos
  stage: image
  variables:
    ARCHITECTURE: arm64
    SUITE: trixie
  script:
    # initramfs for CI
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            ci-initramfs.yaml

    # rootfs for CI
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            ci-rootfs.yaml

rk3588 images:
  extends: .debos
  stage: image
  variables:
    ARCHITECTURE: arm64
    SUITE: trixie
  script:
    # download u-boot and kernel from GitLab artifacts
    - ./download-rk3588-artifacts.sh

    # ospack
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            ospack-debian.yaml

    # rock5b-rk3588 image
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            -t platform:rock5b-rk3588
            image-rockchip-rk3588.yaml
