stages:
  - stage1
  - stage2

.debos:
  image:
    name: ghcr.io/go-debos/debos:main
    entrypoint: [ "" ]
  tags:
    - kvm
  variables:
    ARCHITECTURE: arm64
    SUITE: trixie
  before_script:
    - mkdir -p out
  artifacts:
    expire_in: 1 week
    paths:
      - out

ci image:
  extends: .debos
  stage: stage1
  script:
    # rootfs and initramfs for CI
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            ci-image.yaml

prepare debian rootfs:
  extends: .debos
  stage: stage1
  script:
    # ospack
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            ospack-debian.yaml

rock5b image:
  extends: .debos
  stage: stage2
  needs:
    - "prepare debian rootfs"
  script:
    # download u-boot and kernel from GitLab artifacts
    - ./download-rock5b-artifacts.sh

    # rock5b-rk3588 image
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            -t platform:rock5b-rk3588
            image-rockchip-rk3588.yaml

sige5 image:
  extends: .debos
  stage: stage2
  needs:
    - "prepare debian rootfs"
  script:
    # download u-boot and kernel from GitLab artifacts
    - ./download-sige5-artifacts.sh

    # sige5-rk3576 image
    - debos --artifactdir=out
            -t architecture:$ARCHITECTURE
            -t suite:$SUITE
            -t platform:sige5-rk3576
            image-rockchip-rk3576.yaml
